<a href="https://colab.research.google.com/github/2303a51343/python-for-data-science/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)


[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [2]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


In [3]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[46 67 26 71]
 [95 41 29 39]
 [46 37 50 33]
 [29 69 78 52]]

Row-wise Mean (per student):
 [52.5 51.  41.5 57. ]

Column-wise Mean (per subject):
 [54.   53.5  45.75 48.75]

Standard Deviation of all scores: 19.445436482630058
Variance of all scores: 378.125

Maximum Score: 95
Minimum Score: 26


In [4]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[ 39 242  36]
  [ 13 131 162]
  [162  77 172]]

 [[204  48 133]
  [  8 243 212]
  [191 141 139]]

 [[205 231 233]
  [ 26 200 100]
  [118  63 160]]]

Red Channel:
 [[ 39  13 162]
 [204   8 191]
 [205  26 118]]

Green Channel:
 [[242 131  77]
 [ 48 243 141]
 [231 200  63]]

Blue Channel:
 [[ 36 162 172]
 [133 212 139]
 [233 100 160]]

Average Red: 107.33333333333333
Average Green: 152.88888888888889
Average Blue: 149.66666666666666

Brightened Image:
 [[[ 89 255  86]
  [ 63 181 212]
  [212 127 222]]

 [[254  98 183]
  [ 58 255 255]
  [241 191 189]]

 [[255 255 255]
  [ 76 250 150]
  [168 113 210]]]

Darkened Image:
 [[[  0 192   0]
  [  0  81 112]
  [112  27 122]]

 [[154   0  83]
  [  0 193 162]
  [141  91  89]]

 [[155 181 183]
  [  0 150  50]
  [ 68  13 110]]]
